---

language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible==2.2.1


script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i inventory nxos1.yml --syntax-check
  - ansible-playbook -i inventory nxos1.yml
  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i inventory nxos1.yml 
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

